### ISSUE TITLE
[FEATURE] Anticheat

### ISSUE THREAD

**Issue by Ekinoxx0** [Paradigm-MP/fivem-rust-gamemode#1]
I'm kinda curious about your project, and I would like to give some advice about your anticheat.

It's very important to build it while developing the game mode your making so it fit perfectly your needs.

From what I see now, you are doing client side verification for the spawning of entities : Please don't do that in that way.

This could be easily spoofed or even disable by cheats.
For this specific check, I would recommend using a combination of the two SERVER SIDE events : entityCreating and entityCreated

These cannot be spoofed as they are server side and will greatly simplify your code.

If you have any question, I'm ready to answer them.
In the mean time, good luck for your project 👍

**Comment by benank** [comment]
Thanks for your advice! The current anticheat was written a while ago without onesync and we haven't looked at it since. But you're very right in that anticheat is a very important part of a gamemode like this. Once we're closer to a release, we'll come back to this!

And thanks for your interest in the project - we started it just a few days ago with some resource experimentation (such as chopping down any tree in the game world) and open sourced it just today, so I'm surprised that you found it.

**Comment by Ekinoxx0** [comment]
Oh that's cool 👍
I'm kinda always watching what's new on Github about FiveM so that's how I found it.

Would recommend watching theses events when it will be time to create the anticheat for this gamemode :
startProjectileEvent
ptFxEvent
giveWeaponEvent
entityCreated
entityCreating

Also, entity lockdown mode and server side native to create ped/objects/automobiles are now a thing so that could be useful. (+Getters for peds / vehicles server side)

Will be following the future of this project to see what an oof project of this size will look like 🙂
